// Generated by scripts/weekly.mjs; edit data/reports instead.
import report from '../data/reports/2026-09-11.json';
import type { WeeklyReport } from './market-types';
export const currentReport = report as unknown as WeeklyReport;
